[package]
name = "funds-distributor-api"
version = "0.1.0"
authors = ["MantaDAO"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
cosmwasm-std = "2.0"
cosmwasm-schema = "2.0"
cw4 = "2.0"
thiserror = "1"
